#!/bin/bash

# --- Configuration ---
# Replace this with your actual bearer token
BEARER_TOKEN="eyJhbGciOiJFUzI1NiIsImtpZCI6IjY5NmY0NThjMDAwMDAwMDAwMDAwMDAwMCIsInR5cCI6IngudXNlcitqd3QifQ.eyJhdWQiOlsicGF5bWVudC1zZXJ2aWNlIiwiaW50ZWdyYXRpb24tY29uZmlnLXNlcnZpY2UiLCJjb3Jwb3JhdGUtcG9ydGFsLWFwaSIsIndvbHRhdXRoIiwibG95YWx0eS1nYXRld2F5IiwiZ2lmdC1jYXJkLXNob3AiLCJzdWJzY3JpcHRpb24tc2VydmljZSIsInBlZHJlZ2FsIiwibGlzdC1ldmVyeXRoaW5nLWRhdGFzdG9yZSIsInJlc3RhdXJhbnQtYXBpIiwicmV0dXJucy1hcGkiLCJtZWFsLWJlbmVmaXRzLXNlcnZpY2UiLCJhY3Rpdml0eS1odWIiLCJvcmRlci14cCIsImUtd2FsbGV0LXNlcnZpY2UiLCJ3b2x0LWNvbSIsInBheW1lbnRzLXRpcHMtc2VydmljZSIsImFkLWluc2lnaHRzIiwidG9wdXAtc2VydmljZSIsImRpZmZ1c2lvbiIsImNvbnZlcnNlLXdpZGdldC1jb25zdW1lciIsImRhYXMtcHVibGljLWFwaSIsIm9yZGVyLXRyYWNraW5nIiwidmVudWUtY29udGVudC1hcGkiLCJsb3lhbHR5LXByb2dyYW0tYXBpIiwiY29uc3VtZXItYXNzb3J0bWVudCIsInN1cHBvcnQtZnVubmVsIiwid2xzLWN1c3RvbWVyLXNlcnZpY2UiLCJjb3VyaWVyY2xpZW50Il0sImlzcyI6IndvbHRhdXRoIiwianRpIjoiY2U3YzU1OTRmZWUzMTFmMGI1Y2E5Njc5OWZiZDE3ZWEiLCJ1c2VyIjp7ImlkIjoiNWEzODU5YjdkNzU4YzgwMDBhODU5NDAyIiwibmFtZSI6eyJmaXJzdF9uYW1lIjoiTWF4IiwibGFzdF9uYW1lIjoiUyJ9LCJlbWFpbCI6InNhZHVyc2tpc0BpY2xvdWQuY29tIiwicm9sZXMiOlsidXNlciJdLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfbnVtYmVyX3ZlcmlmaWVkIjp0cnVlLCJjb3VudHJ5IjoiTFZBIiwicGVkcmVnYWxfaWQiOiI1NWNjNjZiYy0xMWQ1LTQxNjMtYTA4Yy05OGUyMGIwZmI1MDgiLCJsYW5ndWFnZSI6Imx2IiwicGVybWlzc2lvbnMiOltdLCJwaG9uZV9udW1iZXIiOiIrMzcxMjY3MTcxOTkiLCJ0ZW5hbnQiOiJ3b2x0IiwicHJuIjoicHJuOnYxOndvbHQ6aWRlbnRpdHk6dXNlcjo1YTM4NTliN2Q3NThjODAwMGE4NTk0MDIifSwiaWF0IjoxNzY5ODkxNDgyLCJleHAiOjE3Njk4OTMyODIsImFtciI6W10sInNpZCI6IjY5N2U1OGFmYTA1ZDY0YjAwYmRjY2U1ZSJ9.FVmvnsos0S4MoovVD3Bn2HDJ4dos39fz_pYJqQIIXQhyrk5-VIMPEbOnyxeZEEGrPjZNfutwZ4lhaGE-3atLvA"

# List of endpoints to call
# Add your specific endpoint URLs to this list
ENDPOINTS=(
    "https://restaurant-api.wolt.com/v1/user/me"
    "https://consumer-api.wolt.com/order-xp/web/v1/pages/orders"
)

# --- Script ---
echo "Starting continuous monitoring. Will run once per minute until a non-200 status is found."
echo "Press Ctrl+C to stop."
echo "========================================